export const TypesEmployees = {
    GET_ALL_EMPLOYEES: "GET_ALL_EMPLOYEES",
    ADD_EMPLOYEE: "ADD_EMPLOYEE",
    EDIT_EMPLOYEE: "EDIT_EMPLOYEE",
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
    SEARCH_EMPLOYEES: "SEARCH_EMPLOYEES",
    UPLOAD_FILE_REQUEST: "UPLOAD_FILE_REQUEST",
}

export const TypeCertificates = {
    GET_CERTIFICATE_BY_ID: "GET_CERTIFICATE_BY_ID",
    GET_CERTIFICATE_BY_EMPLOYEE: "GET_CERTIFICATE_BY_EMPLOYEE",
    ADD_CERTIFICATE: "ADD_CERTIFICATE",
    EDIT_CERTIFICATE: "EDIT_CERTIFICATE",
    DELETE_CERTIFICATE: "DELETE_CERTIFICATE",
}

export const TypeFamily = {
    GET_FAMILY_BY_ID: "GET_FAMILY_BY_ID",
    GET_FAMILY_BY_EMPLOYEE_ID: "GET_FAMILY_BY_EMPLOYEE_ID",
    ADD_FAMILY: "ADD_FAMILY",
    EDIT_FAMILY: "EDIT_FAMILY",
    DELETE_FAMILY: "DELETE_FAMILY",
}

export const TypeExperience = {
    GET_EXPERIENCE_BY_ID: "GET_EXPERIENCE_BY_ID",
    GET_EXPERIENCE_BY_EMPLOYEE_ID: "GET_EXPERIENCE_BY_EMPLOYEE_ID",
    ADD_EXPERIENCE: "ADD_EXPERIENCE",
    EDIT_EXPERIENCE: "EDIT_EXPERIENCE",
    DELETE_EXPERIENCE: "DELETE_EXPERIENCE",
}

export const TypeSalaryIncrease = {
    GET_SALARY_INCREASE_BY_ID: "GET_SALARY_INCREASE_BY_ID",
    GET_SALARY_INCREASE_BY_EMPLOYEE_ID: "GET_SALARY_INCREASE_BY_EMPLOYEE_ID",
    GET_SALARY_INCREASE_BY_LEADER: "GET_SALARY_INCREASE_BY_LEADER",
    ADD_SALARY_INCREASE: "ADD_SALARY_INCREASE",
    EDIT_SALARY_INCREASE: "EDIT_SALARY_INCREASE",
    DELETE_SALARY_INCREASE: "DELETE_SALARY_INCREASE",
}

export const TypeProcess = {
    GET_PROCESS_BY_ID: "GET_PROCESS_BY_ID",
    GET_PROCESS_BY_EMPLOYEE_ID: "GET_PROCESS_BY_EMPLOYEE_ID",
    GET_PROCESS_BY_LEADER: "GET_PROCESS_BY_LEADER",
    ADD_PROCESS: "ADD_PROCESS",
    EDIT_PROCESS: "EDIT_PROCESS",
    DELETE_PROCESS: "DELETE_PROCESS",
}

export const TypeProposal = {
    GET_PROPOSAL_BY_ID: "GET_PROPOSAL_BY_ID",
    GET_PROPOSAL_BY_EMPLOYEE_ID: "GET_PROPOSAL_BY_EMPLOYEE_ID",
    GET_PROPOSAL_BY_LEADER: "GET_PROPOSAL_BY_LEADER",
    ADD_PROPOSAL: "ADD_PROPOSAL",
    EDIT_PROPOSAL: "EDIT_PROPOSAL",
    DELETE_PROPOSAL: "DELETE_PROPOSAL",
}